# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SaniBidStarSD
                                 A QGIS plugin
 Sistemas de Tratamento de Águas Residuárias Simplificados e Descentralizados.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-29
        copyright            : (C) 2021 by UFBA/BID
        email                : ufba@ufba.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SaniBidStarSD class from file SaniBidStarSD.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SaniBidStarSD import SaniBidStarSD
    return SaniBidStarSD(iface)
