MIN_NUM_COMPART_RAC = 4
MAX_NUM_COMPART_RAC = 6

MIN_WIDTH_SHAFTS = 0.25

MIN_TDH = 6
MAX_TDH = 12

MIN_TIME_REMOVAL_SLUDGE = 12

MIN_SEDIMENTATION_TANK_WIDTH = 0.8

MIN_SEDIMENTATION_TANK_DEPTH = 1.2
MAX_SEDIMENTATION_TANK_DEPTH = 2.8
